// Code generated by fw astp autoreg; DO NOT EDIT.
package main

import (
	"github.com/linxlib/fw/v2/app"
	autopkg1 "github.com/linxlib/fw/v2/cmd/example/controllers"
	autopkg2 "github.com/linxlib/fw/v2/cmd/example/middlewares"
	autopkg3 "github.com/linxlib/fw/v2/cmd/example/services"
)

func init() {
	app.RegisterAutoRegistrar(func(e *app.Engine) error {
		e.Container().Map(&autopkg3.DemoDB{})
		e.Container().Map(autopkg3.NewUserService())
		e.Use(&autopkg2.AuthorizationMiddleware{})
		e.Use(&autopkg2.LogMiddleware{})
		e.RegisterMiddleware(&autopkg2.SSEMiddleware{})
		e.RegisterMiddleware(&autopkg2.WebSocketMiddleware{})
		e.RegisterController(&autopkg1.UserController{})
		return nil
	})
}
