package options

import (
	"github.com/jinzhu/configor"
	"log"
	"net"
)

type ServerOption struct {
	intranetIP            string
	Dev                   bool   `yaml:"dev" default:"true"`
	Debug                 bool   `yaml:"debug" default:"true"`
	NoColor               bool   `yaml:"nocolor" default:"false"`
	BasePath              string `yaml:"basePath" default:"/"`
	Listen                string `yaml:"listen" default:"127.0.0.1"` //监听地址
	Name                  string `yaml:"name" default:"fw"`          //server_token
	ShowRequestTimeHeader bool   `yaml:"showRequestTimeHeader,omitempty" default:"true"`
	RequestTimeHeader     string `yaml:"requestTimeHeader,omitempty" default:"Request-Time"`
	Port                  int    `yaml:"port" default:"2024"`
	AstFile               string `yaml:"astFile" default:"gen.json"` //ast json file generated by github.com/linxlib/astp. default is gen.json
}

func ReadConfig(o *ServerOption) {
	o.intranetIP = getIntranetIP()
	err := configor.New(&configor.Config{
		AutoReload: true,
		ENVPrefix:  "FW",
	}).Load(o, "config/config.yaml")
	if err != nil {
		panic(err)
		return
	}

}

func getIntranetIP() string {
	conn, err := net.Dial("udp", "114.114.114.114:80")
	if err != nil {
		log.Fatal(err)
	}
	defer conn.Close()

	localAddr := conn.LocalAddr().(*net.UDPAddr)

	return localAddr.IP.String()
}
