package astp

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

const DefaultAutoRegOutputFile = "fw_autoreg_gen.go"

type AutoRegGenerator struct {
	parser       *Parser
	ExportedOnly bool
}

type autoRegItem struct {
	PkgPath  string
	TypeName string
	Alias    string
	CtorName string
	IsGlobal bool
}

func NewAutoRegGenerator() *AutoRegGenerator {
	return &AutoRegGenerator{parser: NewParser()}
}

func (g *AutoRegGenerator) Generate(dir string, outputFile string) error {
	g.parser.ExportedOnly = g.ExportedOnly
	absDir, err := filepath.Abs(dir)
	if err != nil {
		return fmt.Errorf("get absolute path: %w", err)
	}

	project, err := g.parser.ParseProject(absDir)
	if err != nil {
		return fmt.Errorf("parse project: %w", err)
	}

	if outputFile == "" {
		outputFile = filepath.Join(absDir, DefaultAutoRegOutputFile)
	} else if !filepath.IsAbs(outputFile) {
		outputFile = filepath.Join(absDir, outputFile)
	}

	content, err := buildAutoRegSource(project)
	if err != nil {
		return err
	}
	if err := os.WriteFile(outputFile, content, 0644); err != nil {
		return fmt.Errorf("write autoreg file: %w", err)
	}
	return nil
}

func buildAutoRegSource(project *Project) ([]byte, error) {
	if project == nil {
		return nil, fmt.Errorf("project is nil")
	}

	var services []autoRegItem
	var controllers []autoRegItem
	var middlewares []autoRegItem
	imports := map[string]string{}

	pkgs := make([]*Package, 0, len(project.Packages))
	for _, pkg := range project.Packages {
		pkgs = append(pkgs, pkg)
	}
	sort.Slice(pkgs, func(i, j int) bool { return pkgs[i].Path < pkgs[j].Path })

	aliasSeq := 0
	importAlias := func(pkgPath string) string {
		if a, ok := imports[pkgPath]; ok {
			return a
		}
		aliasSeq++
		a := fmt.Sprintf("autopkg%d", aliasSeq)
		imports[pkgPath] = a
		return a
	}

	for _, pkg := range pkgs {
		types := make([]*Type, 0, len(pkg.Types))
		for _, typ := range pkg.Types {
			types = append(types, typ)
		}
		sort.Slice(types, func(i, j int) bool { return types[i].Name < types[j].Name })

		for _, typ := range types {
			if typ == nil || typ.Kind != KindStruct {
				continue
			}
			hasService := hasDocAnnotation(typ.Doc, "Service")
			hasController := hasDocAnnotation(typ.Doc, "Controller")
			hasMiddleware := hasDocAnnotation(typ.Doc, "Middleware")
			if !hasService && !hasController && !hasMiddleware {
				continue
			}
			disabled := hasDocAnnotation(typ.Doc, "Disable")
			if disabled {
				continue
			}
			alias := importAlias(pkg.Path)
			ctor := findZeroArgConstructor(pkg, typ)
			if hasService {
				services = append(services, autoRegItem{PkgPath: pkg.Path, TypeName: typ.Name, Alias: alias, CtorName: ctor})
			}
			if hasController {
				controllers = append(controllers, autoRegItem{PkgPath: pkg.Path, TypeName: typ.Name, Alias: alias, CtorName: ctor})
			}
			if hasMiddleware {
				middlewares = append(middlewares, autoRegItem{PkgPath: pkg.Path, TypeName: typ.Name, Alias: alias, CtorName: ctor, IsGlobal: hasDocAnnotation(typ.Doc, "Global")})
			}
		}
	}

	importPaths := make([]string, 0, len(imports))
	for path := range imports {
		importPaths = append(importPaths, path)
	}
	sort.Strings(importPaths)

	var b bytes.Buffer
	b.WriteString("// Code generated by fw astp autoreg; DO NOT EDIT.\n")
	b.WriteString("package main\n\n")
	b.WriteString("import (\n")
	b.WriteString("\t\"github.com/linxlib/fw/v2/app\"\n")
	for _, path := range importPaths {
		b.WriteString("\t")
		b.WriteString(imports[path])
		b.WriteString(" ")
		b.WriteString(strconv.Quote(path))
		b.WriteString("\n")
	}
	b.WriteString(")\n\n")
	b.WriteString("func init() {\n")
	b.WriteString("\tapp.RegisterAutoRegistrar(func(e *app.Engine) error {\n")
	for _, s := range services {
		b.WriteString("\t\te.Container().Map(")
		b.WriteString(newExpr(s))
		b.WriteString(")\n")
	}
	for _, m := range middlewares {
		if m.IsGlobal {
			b.WriteString("\t\te.Use(")
			b.WriteString(newExpr(m))
			b.WriteString(")\n")
		} else {
			b.WriteString("\t\te.RegisterMiddleware(")
			b.WriteString(newExpr(m))
			b.WriteString(")\n")
		}
	}
	for _, c := range controllers {
		b.WriteString("\t\te.RegisterController(")
		b.WriteString(newExpr(c))
		b.WriteString(")\n")
	}
	b.WriteString("\t\treturn nil\n")
	b.WriteString("\t})\n")
	b.WriteString("}\n")

	fmted, err := format.Source(b.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated autoreg source: %w", err)
	}
	return fmted, nil
}

func newExpr(it autoRegItem) string {
	if it.CtorName != "" {
		return it.Alias + "." + it.CtorName + "()"
	}
	return "&" + it.Alias + "." + it.TypeName + "{}"
}

func findZeroArgConstructor(pkg *Package, typ *Type) string {
	if pkg == nil || typ == nil {
		return ""
	}
	name := "New" + typ.Name
	fn := pkg.Functions[name]
	if fn == nil {
		return ""
	}
	if len(fn.Params) != 0 || len(fn.Results) == 0 {
		return ""
	}
	ret := fn.Results[0]
	if ret == nil || ret.Type == nil {
		return ""
	}
	if !strings.EqualFold(ret.Type.Name, typ.Name) {
		return ""
	}
	if ret.Type.Kind != KindPointer && ret.Type.Kind != KindStruct {
		return ""
	}
	return name
}

func hasDocAnnotation(doc *CommentGroup, target string) bool {
	if doc == nil {
		return false
	}
	for _, ann := range doc.ParsedAnnotations {
		if ann == nil {
			continue
		}
		if strings.EqualFold(strings.TrimSpace(ann.Name), target) {
			return true
		}
	}
	for _, ann := range doc.Annotations {
		if strings.EqualFold(strings.TrimSpace(ann), target) {
			return true
		}
	}
	return false
}
